CREATE VIEW ARTICULOS_SUCURSAL_1 (ARTICULOS, NOMBRE_SUCURSAL, UBICACION_SUCURSAL)

/* en esta vista mostramos todos los articulos que se venden en la sucursal 1 */

AS SELECT a.COD, suc.NOMBRE, suc.UBICACION
FROM ARTICULO a INNER JOIN SE_VENDE_EN s ON a.COD = s.COD 
    INNER JOIN SUCURSAL suc ON s.ID = suc.ID 
    WHERE s.ID = 1;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ARTICULOS_SUCURSAL_1 TO  SYSDBA WITH GRANT OPTION;

