CREATE DOMAIN DOM_RESULTADO
/*CREAMOS UN DOMINIO CON LOS VALORES LOCAL, VISITANTE, O EMPATE
PARA DELVOLVER EL RESULTADO DEL PARTIDO*/
 AS varchar(255)
 check (VALUE = 'LOCAL' or 
        VALUE = 'VISITANTE' or VALUE = 'EMPATE')
 COLLATE NONE;
