CREATE VIEW RESULTADO_PARTIDO (IDPARTIDO, GOLES_LOCAL, GOLES_VISITANTE, RESULTADO)
/*EN ESTA VISTA DEVOLVEMOS EL ID DEL PARTIDO, LA CANTIDAD DE GOLES DE CADA EQUIPO Y EL RESULTADO DEL PARTIDO*/
AS select gl.IDPARTIDO, gl.CANT_GOLES, gv.CANT_GOLES, F_resultado(gl.CANT_GOLES, gv.CANT_GOLES) from 
    GOLES_EQUIPO_LOCAL gl inner join GOLES_EQUIPO_VISITANTE gv on gl.IDPARTIDO = gv.IDPARTIDO;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON RESULTADO_PARTIDO TO  SYSDBA WITH GRANT OPTION;

